import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Cutive } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

const cutive = Cutive({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${cutive.className}  antialiased  bg-[#F8F4E1]`}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
